#12 - add header
scrap-masters/frontend pull request #17
Opened 2022-11-17 20:14 UTC by JakubZakowicz

2022-11-17 22:31 UTC, shiragaira commented
@JakubZakowicz Dlaczego usunąłeś mnie z tego PR? Jest work in progress?

2022-11-18 21:20 UTC, shiragaira requested changes
Zmiany obgadane na Live Code Review

2022-11-19 16:25 UTC, shiragaira requested changes

2022-11-19 16:25 UTC, shiragaira commented on src/routing/routes.ts
> +  findEmployeeRoute: () => "/szukaj-pracownika"
Nie potrzebny dopisek `Route`, obiekt `routes` z góry nam mówi że są to scieżki

2022-11-19 16:25 UTC, shiragaira commented on src/components/Header/Header.test.tsx
> +    expect(screen.getByText("CWUP - Plan zajęć")).toBeInTheDocument()
Tutaj raczej bym sprawdzał czy jest element `h1` zamiast bezpośrednio tekstu prawdopodobnie coś w stylu `.getByRole('header')`

2022-11-19 18:17 UTC, JakubZakowicz commented on src/components/Header/Header.test.tsx
> +    expect(screen.getByText("CWUP - Plan zajęć")).toBeInTheDocument()
Coś takiego może być?

2022-11-20 11:30 UTC, shiragaira approved these changes

2022-11-20 11:31 UTC, merged