#11 - add footer
scrap-masters/frontend pull request #18
Opened 2022-11-17 21:06 UTC by JakubZakowicz

Should close #11

2022-11-17 22:30 UTC, shiragaira requested changes

2022-11-17 22:30 UTC, shiragaira commented on src/components/Footer.tsx
> +    <div className="bg-black py-16 text-white">
Do stopki jest specjalny tag <footer>, zawsze starajmy się wykorzystywać nowoczesny HTML i jego dobra.

2022-11-17 22:30 UTC, shiragaira commented on src/components/Footer.tsx
> +export default Footer
Polecam jednak exportować pliki w trochę inny sposób, który nie zaszkodzi a może zaprocentować w przyszłości (może nie na tym projekcie ale na doświadczeniu). 
W folderze `./components` trzymamy foldery dla każdego komponentu, w tym folderze natomiast dwa pliki `./Footer.tsx` oraz `./index.ts`, w pliku `./index.ts` jedyne co mamy to linijkę `export * from './Footer'`, natomiast w pliku `./Footer.tsx` lepiej zrobić na górze `export const Footer ...`

2022-11-18 15:46 UTC, JakubZakowicz commented on src/components/Footer.tsx
> +    <div className="bg-black py-16 text-white">
Nie wierzę,że taki bląd popełniłem xD. Chyba zajmowanie się backendem przez ostani czas nie najlepiej wpływa na frontend

2022-11-18 15:51 UTC, JakubZakowicz commented on src/components/Footer.tsx
> +export default Footer
Zrobione. Btw. ja się spotkałem jedynie z taką wersją, że w folderze `./components` tworzysz plik `./index.ts`, i z tego pliku eksportujesz wszystkie komponenty, co wydaje mi się bardziej pomocne, w sytuacji kiedy na jednej stronie musisz zaimportować dużo komponentów.

2022-11-18 17:33 UTC, shiragaira commented on src/components/Footer.tsx
> +export default Footer
Tak wiem, to też jest opcja, możliwe nawet że lepsza w naszym wypadku, ale chciałem przedstawić Ci też ten sposób bo to mój ulubiony i uważam go za najbardziej skalowalnego. Dla przykładu mam teraz tak naprawdę tylko plik komponenty u index, na innych projektach już masz inaczej bo np w tym folderze masz komponent, index, plik graphql, hook do komponentu, utils i testy i coś jeszcze i wtedy masz folder z komponentem oraz jego wszystkimi powiązaniami w jednym miejscu. Nawet w tym momencie możesz wyciągnąć cały folder i zrobić z niego jakąś osobną paczkę (po lekkiej modyfikacji pewnie).

2022-11-18 17:44 UTC, shiragaira approved these changes

2022-11-18 17:45 UTC, merged